const data = [
    {
        img:"https://img3.aksam.com.tr/imgsdisk/2021/04/30/t25_koc-burcu-insani-ozellikl-837.jpg"


        ,
        title: "Koç Burcu/ 21 Mart- 20 Nisan",
        desc: "Evet koç burucun en bilinen özelliği 'egoistlik 'özelliğidir.Bunun yanında cesaretli ve önderlik özellikleri de oldukça fazladır. Duygusal olmayan bu burcun insanlar kolay bir şekilde yaşam sürerler.Bu burcun etkisi altında doğan kişiler yaşamayı seven, coşkulu, girişken yapıya sahiptir. Yeni şeyleri öğrenmeye karşı çok heveslidirler. Yaratıcı bir meraka sahiptirler. İlgilendikleri konuda üretken oldukları kadar yaptıklarının başkaları tarafından onaylanması da onlar için önem taşır.Heyecanlı yapıları yüzünden çabuk hareket eden, pratik tiplerdir. En zor koşullara bile katlanabilen savaşçı nitelikleri vardır. İstediklerini elde edemezler ya da yanlış anlaşılırlarsa kolayca öfkelenebilirler. Ancak öfkeleri saman alevi gibi çabuk geçer. Kin tutmazlar ve hatalarını anladıkları zaman kalpleri kazanmak için her şeylerini verebilirler.",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/12/boga-burcu-ve-dogal-taslari-.jpeg-1132x800.jpg"
        ,
        title: "Boğa Burcu /21 Nisan 21 Mayıs",
        desc: "Boğa burcu tüm burçlar arasında en azimli, ' en katı ve en inatçı burçtur. ' Tuttuğunu koparan bu burç yapması gereken şeyler yapmakta zorlanır.Boğa ilişkilerinde güvenlik ve sağlamlık arar. Uzun vadeli düşünür ve sadakata inanır. Yatıştırıcı, huzur verici bir yapısı vardır. Ancak aynı zamanda sahip olmacıdır ve güvensiz hissederse güçlü bir kıskançlık sergileyebilir. Yapıcı ve kararlı olması ona ilişkilerinde uzun vadeli, kazançlı sonuçlar getirir.Kararlı ve güven vericidir. Zevk sahibi olması, barışa ve uyuma önem vermesi en iyi özellikleridir.  Fiziksel açıdan güçlüdür. Verimli ve ortaklaşa çalışmalarda yaratıcıdır.Ancak Boğa’nın  İnatçılığı ve akılsızca direnişi zayıf yönüdür. Bu durum kıskançlık söz konusu olduğunda ilişkilerde kilitlenme yaratabilir. Yeteri kadar yaratıcı ve esnek düşünemeyebilir. Daha fazla esnekliğe ve hayal gücüne ihtiyacı vardır. Sabitliği yüzünden kendini geliştirmekte zorlanabilir.Venüs’ün burcu olan Boğa dişil, manyetik çekiciliğe sahip bir burçtur. Çok fazla söze girip, olayı karmaşıklaştırmadan, açık bir tavırları vardır. Boğa’lar uzun vadeli ilişkileri tercih ederler.",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2021/01/ikizler-burcu-ozellikleri-ve-dogal-taslari-1132x800.jpg",
        title: "İkizler Burcu /22 Mayıs 22 Haziran",
        desc: "En bilinen özellikleri: Bulunduğu ortama ayak uydurur, ' konuşkan ve dinamik ' bir ruha sahiptir.İkizle burçları çok yönlü ve renkli bir kişiliğe sahiptir. Öğrenmek onun için nefes almak gibidir. Durağanlığa dayanamaz, kolay sıkılır. Çabuk düşünür ve çabuk hareket ederler. Hemen her konuda bilgi sahibi olmayı severler. Bir konuda bilgileri az bile olsa, bilgiyi ortaya koyuşlarında ki ustalıkları sayesinde çok iyi biliyormuş gibi görünebilirler. Konuşmada ve kelimeleri sıralamada ustalıkları sebebiyle etkileyici konuşmacılardır.İkna yeteneğine sahip olduğu gibi çok esprilidir. Hazırcevap ve muziptir, eğlendiricidir.",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/06/yenge%C3%A7-burcu.jpeg-1133x800.jpg",
        title: "Yengeç Burcu /23 Haziran 22 Temmuz",
        desc: "Yengeç burcun insanı burçların arasında en anaç sıcakkanlı olan burçtur. 'Dikkatli ve sevecen '' olan bu burç sevdiğini sahiplenir.Yengeç burçları çocuk gibi yumuşak, duygusal açıdan besleyen ve beslenen bir yapıdadır. Duygularla hareket eder ve sevdiklerini çok korur, onlara kalbinde özel bir yer açar. Son derece koruyucudur.Duygusal durumu sürekli değişim içinde olduğu için kolayca depresif olabilir, kendini olumsuz duygulardan kurtarması ve güven kazanması uzun zaman alacaktır. Dışarı karşı sert bir görünüm sergileseler de, hassas ve koruyucu bir doğaları vardır. Çok yumuşak ve iyi kalplilerdir. Ama kırılgan doğalarını korumak için burçlarının simgesi gibi kabuklarına çekilebilirler. Anlaşılması zor karmaşık insanlardır. Zor duruma düştüklerinde bazen çok güçlü ve cesur, bazense çocuk gibi zayıf ve savunmasız olabilirler. Dengede kalabilmeleri için onlara mutlu bir yuva ve güvenlik gereklidir.",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/07/aslan-burcu-ve-do%C4%9Fal-ta%C5%9Flar%C4%B1-.jpeg.jpg",
        title: "Aslan Burcu /23 Temmuz 22 Ağustos",
        desc: "Her şeye karışan, sıcak kanlı, yetenekli olan bu burcun insanı oldukça 'sabırsızdır.Aslan burçları yüce gönüllü ve öne çıkan karakterleri ile diğer burçlardan ayrılırlar. Yönetmeyi ve her zaman odak noktası olmayı severler. Bazen ise bir çocuk gibi oyuncu ve hayatı seven ve bunu yansıtan bir karakteri vardır.Başkalarına ilham veren, etkileyici, iyimser, güleryüzlü, hareketli, güneş gibi çevresine ışık saçan sıcak tiplerdir. Mücadele ederken her zaman dürüst ve mertçe davranır, kurnazlık düşünmezler. Bağışlayıcı olmalarına karşın bazen aşırı gururlarının etkisi altında kalabilirler.Lükse ve ihtişama düşkündürler. Aşırı gururları bazen kendilerini olduklarında daha yüksekte görmelerine de sebep olabilir. Buna karşın affedici yönleri vardır. Güçsüz ya da zor durumda kalmış yardıma ihtiyacı olan kişilere karşı iyi davranırlar. Eli açık ve bonkördürler. '",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/08/ba%C5%9Fak-burcu-ve-do%C4%9Fal-ta%C5%9Flar-.jpeg.jpg",
        title: "Başak Burcu /23 Ağustos 22 Eylül",
        desc: "Her şeyi kafasına takan bu burcun insanı; ' titiz, zeki ' ve her zaman her şeyin en iyisini isterBaşak burçları çalışkan, düzenli ve pratik insanlardır. Düzen, sistem ve organizasyon onlar için çok önemlidir. Organizasyon konusunda onların üstüne yoktur. Ayrıntılara dikkat ederler. Mükemmeliyetçi bir yapıları olduğu gibi, bazen bu sebeple çevrelerine karşı aşırı eleştirici de davranabilirler. Sağlıklarına oldukça düşkündürler. Sadece fiziken değil, mental ya da ruhsal yönden de sağlıklı olmak isterler. Çoğu Başak burcu doğal ilaçlara, sebzelere ve bitkisel tedavilere ilgi duyar. Araştırmacı ve öğrenmeyi seven bir yapıları vardır. Çoğunlukla gerçekçi ve elle tutulur sonuçlara güvenirler. Sorgulayıcı ve inceleyicidir. Aslında bilgiyi arayan başak burçları için bu sorgulayıcılık bazen tutuculuğa dönüşerek önlerinde bir engel oluşturabilir.Çevrelerinde temizliğe ve hijyene önem verirler..",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/11/terazi-burcu-ve-dogal-taslar-.jpeg.jpg",
        title: "Terazi Burcu/ 23 Eylül 23 Ekim",
        desc: "Terazi Burcu Başkaların sözüne uyan kararlarını hemen değiştirebilen bu burcun insanı 'ağır başlı ' ve 'diplomatik ' bir yapısı vardır. Terazi burcu denge ve adalet burcu olarak bilinir. Teraziler çevrelerinde uyum ve barışçıl bir atmosfer yaratma konusunda yeteneklidirler. İlişkilerinden olumlu bir sonuç çıkarabileceklerine inanırlar. Adalet duyguları fazlasıyla gelişmiş olduğu için haksızlıklara dayanamazlar ve bu yolda hemen tepki verebilirler. Bu burçtan pek çok sosyal alanda eylemci ya da hukukçu çıkar. Terazilerde çevrelerin güzellik yaratma kabiliyeti vardır. Aynı zamanda sanat ve güzellik duygusu hayatlarında önemli bir yer tutar. Adeta dokundukları her şeye rafine bir güzellik ve uyum getirebilirler. Dekorasyonda yeteneklidirler.Terazi burcu kendisinden önce başkalarına odaklanabilen bir burçtur. İşbirliğine, ortaklıklara her zaman açık durabilirler. İdeal eşler ve ortaklardır. Yalnız kalmak onlara göre değildir.",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/10/akrep-burcu-ve-dogal-taslari-.jpeg-1132x800.jpg",
        title: "Akrep Burcu/24 Ekim 22 Kasım",
        desc: "Akrep burcu aşırı uçları yaşayabilen çözümlenmesi zor bir burçtur. Bu burcun insanı fiziksel olduğu kadar derin bir içsel güce sahiptir. Akrep insanı yüksek bir kişisel çekim, derinlik ve güç sahibi olma arzusu taşır. Ayrıca sınırları da zorlayan bir burçtur. Her koşulda kendini yenileme gücüne sahiptir. Tehlikeli ya da zor koşullarda bile hedefinden şaşmadan kararlılıkla iç ve dış mücadelesini sürdürebilir. İşlerini tek başına yapmaktan hoşlanırlar, yalnızlık onları hiç sıkmaz. Sabırlı ve özenli çalışırlar ve bitmez bir enerjileri vardır. Sezgileri güçlüdür. Bir insan ya da bir olayı bir bakışta derinlemesine kavrayabilirler. Kimi zaman düşüncelerini patavatsız şekilde söyleyerek kırıcı olabilirler. Öfkelendiklerinde acı konuşurlar ve karşılarındakinin hiç aklına gelmeyen zayıf yanlarını bir çırpıda döküverirler. İnsanlarla ilişkilerinde sahiplenici ve ele geçirici olabilirler. Kimi zaman baskıcı, domine edici ve kıskanç tavırlar sergileyerek hayatı hem kendileri hem de çevreleri için zorlaştırırlar. Ancak yine de akrep insanı kilitli bir kutu gibidir ve kendi hakkında bilinmesini istemediği şeyleri gizlemekte ustadır. Su grubundan olmalarına rağmen duygularını gizlerler. Ser verip sır vermezler. Akrepler en zor olaylardan sonra dahi kendilerini yenilebilme gücüne sahiptir. Yaşamın anlamı, ölüm ve ölümden sonrası gibi konular doğal ilgi alanıdır. ",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/12/yay-burcu-ozellikleri-ve-dogal-taslari-.jpeg.jpg",
        title: "Yay Burcu/ 23 Kasım 21 Aralık",
        desc: "Özgürlüğü seven, ' komik ' ve 'dürüst ' olan bu burcun insanı dikkatsiz ve oldukça batıl inançlara inanır.Yay burcu iyimserlik ve yeniliklere açıklıkları ile tanınırlar. Yaşama karşı coşkulu ve idealist kişilerdir. Kavrayışları güçlü olduğu için felsefi konularda başarılı olurlar. Gezmeyi, seyahati, farklı yerler görüp farklı kültürler tanımayı çok severler. Yerlerinde duramayan değişiklik yapmayı seven tiplerdir. Yay aynı zamanda değişken bir burçtur ve bu değişkenlikleri onlara davranışlarında tutarsızlık getirebilir. Kolayca karasızlık yaşayabilirler. Çoğunlukla idealist yapıda oldukları için öğrenmeye, öğrendiklerini pratik etmeye ve kendilerini geliştirmeye çalışırlar. Ancak çok kolayca sıkılıp yeni bir yol izlemeye de başlayabilirler. Yay burcu arayış içinde bir burçtur. Gerçeği, bilgiyi ve bilgeliği ararlar. Güçlü bir doğru- yanlış anlayışları vardır. Hayatlarında bu doğrulara uygun yaşamaya çalışan adil, ahlaklı ve erdemli kişiler yaylardan çıkar. İnançları güçlüdür. Ancak abartıya yatkın olduğu için dogmatik ve fanatik olma tehlikesi de vardır.",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/11/oglak-burcu-ve-dogal-taslari-.jpeg.png",
        title:"Oğlak Burcu /22 Aralık 20 Ocak",
        desc: "Kıskançlığıyla bilinen bu burcun insanı; ' komik, dikkatli, sıcakkanlı ve azimlidir. Oğlak burçları ciddi, güvenilir, sorumluluk sahibi olmaları ve yılmadan çalışmaları ile tanınırlar. Gelişmiş bir görev duyguları vardır. Çok genç yaştan itibaren omuzlarına sorumluluk yüklenmeye ve çalışmaya başlayabilirler. Ancak çok iyi birer iş adamı-kadını olabilirler. Yöneticilik yetenekleri çok gelişmiştir. Oğlaklar çok disiplinlidir. Hedeflerine ulaşmak için yılmadan çalışırlar. Kolay kolay gevşeyemeyen bir yapıları vardır. Kolayca güvensizliğe, karamsarlığa kapılabilirler. Genellikle çok genç yaşlarında başlayan yetişkin hayatları sebebiyle somurtkan ve ciddi tiplerdir. Ancak oğlaklar yaşları ilerledikçe çocuklaşırlar. Fiziksel görünümleri, yaşlansalar dahi genç kaldığı gibi, edindikleri deneyimlerin ışığında yaşlandıkça bilgeleşerek çocuklar gibi sadeleşebilirler. Genellikle duygularını göstermeyen, derinlerde yaşayan, maddi güvenliğe önem veren insanlardır. Maddi durumları iyi değilse kolayca endişelenip, kendilerine olan güvenlerini yitirebilirler.'",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2020/10/kova-burcu-ana-gorsel-.jpeg.jpg",
        title: "Kova Burcu/ 21 Ocak 18 Şubat",
        desc: "Tek başına hareket etmeyi seven bu burcun insanı 'orijinal, yetenekli ve duygusuzdur.'Kova burçları hümanist, insanlık için çalışmalar yapan, toplumsal meselelerle ilgilenen ve aynı zamanda yenilikçi ve idealist kişilerdir. Akılcı oldukları için sadece hayal kurmakla kalmaz ideallerini gerçeğe dönüştürmek için organizasyonların içinde olmayı tercih ederler. Kollektif olan herşeyi severler. Yenilik ve değişiklikten yanadırlar. Dünyanın daha iyi bir olaması için çalışırlar.Hem kişisel hemde kollektif özgürlüklere çok değer verirler. Ancak kova sabit bir burç olduğu için her nekadar modernizmi savunsalarda kendi görüşlerini kolay değiştirmeyen inatçı ve sabit fikirli davranışlarda bulunabilirler. Genellikle görüşleri çağının ötesinde ve sezgiseldir. Hayata bilim adamı gibi yaklaşmayı ve objektif bakmayı severler. Bu yüzden kovalarla yakınlaşmak kolay değildir. Her şeye rağmen insanlarla aralarına mesafe koymayı severler. ",        
    },
    {
        img: "https://soulmeps.com/wp-content/uploads/2021/01/balik-burcu-ozellikleri-ve-faydali-dogal-taslari-.jpeg.jpg",
        title: "Balık Burcu/ 19 Şubat 20 Mart",
        desc: "Burçlar arasında en duygusal olan bu burcun insanı azimli ' kıskanç ve gizemlidir. 'Balık insanı son derece merhametli, uysal ve vicdan sahibi olması ile tanınır. Çok duyarlı olan bu burç insanı dış etkenlerden çok kolayca etkilenebilir ve incinebilir. Hayal gücü çok gelişmiş olması nedeniyle sık sık hayal dünyalarına sığınabilirler. Bu şekilde gerçeklerden kaçma eğilimi taşırlar.Sevimli ve fedakar yapıdadır. İyi kalpli ve merhametli olması sebebiyle balık burçları sık sık zorda kalmış, kendinden daha kötü durumda olan, yardıma nuhtaç kişilere yardım etmeye çalışır. Çok hassas ve sezgileri gelişmiş ve diğer insanların da duygularına karşı empati yeteneği çok gelişmiş bir burçtur balık. Dış görünüş olarak ve davranışları ile sanki bu dünyadan değilmiş gibi bir izlenim verirler. Mücadeleci olmayan kişilikleri ile tartışmalardan hep uzak durmayı tercih ederler. Affedici ve huzura önem veren kişilerdir. Yavaş ve aceleci olmayan tavırları çoğu zaman uyuşukluk olarak nitelendirilir.Mizah duygusu olan, sevilen arkadaşlardır. Kimi zaman neşeli tavırları ile çevrelerine pozitif enerji aşılarlar. Kimi zaman ise kabuklarına çekilirler. Kendine güvensizlik bu burcun özelliklerinden biridir.",        
    },
  
  
]

export default data;